# Generated by Django 6.0 on 2026-02-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Fee in INR', max_digits=8),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
