# Generated by Django 6.0 on 2026-02-01 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorprofile_bio_doctorprofile_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.lab'),
        ),
    ]
