# Generated by Django 6.0 on 2026-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_labtechnicianprofile_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicianprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
