# Generated by Django 6.0 on 2026-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostictest',
            name='category',
            field=models.CharField(choices=[('Blood Tests', 'Blood Tests'), ('Urine Tests', 'Urine Tests'), ('Imaging', 'Imaging'), ('Screening', 'Screening'), ('General', 'General')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='home_collection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='preparation_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='result_duration',
            field=models.CharField(default='24 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='sample_type',
            field=models.CharField(choices=[('Blood', 'Blood'), ('Urine', 'Urine'), ('Saliva', 'Saliva'), ('Swab', 'Swab'), ('Other', 'Other')], default='Blood', max_length=50),
        ),
        migrations.AddField(
            model_name='diagnostictest',
            name='test_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
