# Generated by Django 6.0 on 2026-02-15 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_diagnostictest_category_diagnostictest_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='diagnostic_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.diagnostictest'),
        ),
    ]
