# Generated by Django 6.0 on 2026-02-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_testbooking_result_file_testbooking_result_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbooking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
