# Generated by Django 6.0 on 2026-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_testbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testbooking',
            name='status',
            field=models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending Payment', max_length=20),
        ),
    ]
