# Generated by Django 6.0 on 2026-02-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_testbooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='diagnostic_test',
        ),
        migrations.AddField(
            model_name='payment',
            name='test_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.testbooking'),
        ),
    ]
