# Generated by Django 6.0 on 2026-02-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
